--1
SELECT CIUDAD, TELEFONO
FROM OFICINAS
ORDER BY CIUDAD;

--2
SELECT CODIGOOFICINA, CIUDAD,REGION, PAIS
FROM OFICINAS
WHERE UPPER(PAIS) LIKE 'E%';

--3
SELECT DISTINCT ESTADO
FROM PEDIDOS;

--4
SELECT NOMBRE, APELLIDO1|| ' '||APELLIDO2 AS "APELLIDOS", PUESTO
FROM EMPLEADOS 
WHERE PUESTO ;

--5
SELECT NOMBRECLIENTE, CIUDAD
FROM CLIENTES
WHERE CIUDAD NOT IN (SELECT CIUDAD
                      FROM OFICINAS);

--6
SELECT C.NOMBRECLIENTE AS "Nombre de los Clientes"
FROM CLIENTES C, DETALLEPEDIDOS D
WHERE D.CANTIDAD > 200 ;

--7
SELECT NOMBRECLIENTE, NOMBRECONTACTO || ', '|| APELLIDOCONTACTO AS "Representante"
FROM CLIENTES;

--8
SELECT NOMBRECLIENTE || ', ' || NOMBRECONTACTO AS "Nom Representante"
FROM CLIENTES 
WHERE CODIGOCLIENTE IN (SELECT CODIGOCLIENTE
                          FROM PAGOS );